spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://db1.c04zpvagijdv.ap-southeast-1.rds.amazonaws.com:3306/netsbizsv2
    dbcp2:
      test-on-borrow: true
      validation-query: /* PING */select 1
      max-total: 8
      max-idle: 8
      initial-size: 1
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show.sql: false
  format.sql: true
  new.generator.mappings: false
logging:
  level:
    root: INFO
    org.springframework: ERROR
    com.nets: TRACE
    org.hibernate: ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [id=%X{id}] %logger{36} - %msg [%L]%n"
  file:
    path: logs